### ISSUE TITLE
Unable to run due to dependency issues 

### ISSUE THREAD

**Issue by unoriginalscreenname** [ironWolf1990/Procedural-City-Generation#1]
I'm having a lot of trouble getting the application to run.  I'm seeing some issues related to the dependencies that's preventing it from running.  

I see this when I'm able to load the GUI and hit the run button:
GUI.py:6: MatplotlibDeprecationWarning:
The matplotlib.backends.backend_qt4agg backend was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
The syntax of the command is incorrect.
The syntax of the command is incorrect.
Unhandled Python exception

It just dies when try and run it.

**Comment by anshdavid** [comment]
Hey @ericmcgregor, I dont think `matplotlib` is the issue. I am using version `3.2.2`. I made fixes that might resolve your issue. 

If either `Roadmap Generation` or `Polygon Extraction` fail , re-run the `Roadmap Generation`. You should get an error message in the **GUI** console, so kindly scroll down to see it. It'll take 2-3 tries but it should definitely work

Since the original authors of the program are not maintaining the original repo it might take me some time to push a solid fix after understanding the logic.  

Please reach out if you have any further issues.

**Comment by unoriginalscreenname** [comment]
Hey thanks @ironWolf1990 !  It did take a couple attempts, and it started throwing an error about a missing temp directory and height map file... but then after shutting it down and reloading it did start working.  Pretty cool to see it up and running!

I got as far as the Visualize in Blender when it threw and error in my terminal (not the console) of "'blender' is not recognized as an internal or external command, operable program or batch file."  I haven't had time to poke around with it yet, so thought I would note it here.

**Comment by QAC-Lab** [comment]
You have to install blender

**Comment by anshdavid** [comment]
You have to install blender. If you are using Ubuntu, just install the snap from the store. For other distributions follow their respective instructions.

**Comment by unoriginalscreenname** [comment]
Will this run blender in a windows environment, or only in a linux environment?  I'm currently running it from a windows powershell, but i do have wsl2 setup with an ubuntu distribution available.

**Comment by anshdavid** [comment]
I just went over the code and it definitely should. Could you kindly run to verify ? Don't have Windows installed.

**Comment by unoriginalscreenname** [comment]
Yes.  Ok.  I see now where it says to overwrite the path in blenderize.py with the windows path.   I was able to load that file in blender and run it and it looks like it's working.  very cool.  thank you.

**Comment by anshdavid** [comment]
Nice. Can I close this issue ?
